POST http://localhost:7007/register
Content-Type: application/json

{
    "user": {
        "email": "desmond95malik@gmail.com",
        "password": "password",
        "first_name": "Will",
        "last_name": "Smith",
        "role": "MEMBER"
    }
}

###
POST http://localhost:7007/login
Content-Type: application/json

{
    "email": "desmond95malik@gmail.com",
    "password": "password"
}

###
POST http://localhost:7007/email_verification
Content-Type: application/json

{
    "email": "desmond95malik@gmail.com",
    "token": "05c613dafa6ab41cc0e4efd5eae29b75e14054b530bffeeedad2754720c3cb40"
}